### ISSUE TITLE
Netiek pareizi uzskaitīts pareizais rezultāts

### ISSUE THREAD

**Issue by GundegaDekena** [juris124/heroku-tests#30]
Man liekas, ka problēma ir sekojošā vietā - 
https://github.com/juris124/heroku-tests/blob/4c86a2182388977676fcb661bd6aa91f4732acad/static/js/scripts.js#L26

Kaut kāda iemesla dēļ tur HTML tekstā pievienojas lieka jauna, tukša rinda.
Vajadzētu pielikt klāt `trim()`, šādi - `document.activeElement.textContent.trim()`, tas atrisinātu problēmu. Alternatīvi var mēģināt atrast kur tas pieliekas, bet es pirmajā acu uzmetienā nemanīju, kur varētu būt kļūda templeitos.

@in24 Varbūt varat palūkoties?

**Comment by in24** [comment]
Pieliku .trim(), bet problēma neatrisinājās. Tagad nav laika skatīt citu.

**Comment by GundegaDekena** [comment]
Hmm, jā. Vēl viena lieta - 
```
<div class="preloader behind" style="opacity: 0;">
  <img src="/static/bildes/pulsing-cube.svg">
</div>
```
ir nepareizā vietā, kas noved pie tā, ka pēc testa beigām nevar nospiest navigācijas linkus. Šim divam būtu jābūt starp "navbar-menu" un "saturs" diviem, pašlaik tas ir iekšā "saturs" divā. Tas gan arī neatrisināja šo problēmu, bt vajadzētu salabot :)

**Comment by GundegaDekena** [comment]
> Pieliku .trim(), bet problēma neatrisinājās. Tagad nav laika skatīt citu.

Izskatās, ka .trim() vajag arī pareizajai atbildei - `pareiza[jautajums].trim()`, jo tur arī kaut kādas jocīgas atstarpes parādās.

**Comment by GundegaDekena** [comment]
Viss salabots ar #32
