### ISSUE TITLE
Testa lapās nevar nospiest navigācijas linkus

### ISSUE THREAD

**Issue by GundegaDekena** [juris124/heroku-tests#33]
Hmm, jā. Vēl viena lieta - 
```
<div class="preloader behind" style="opacity: 0;">
  <img src="/static/bildes/pulsing-cube.svg">
</div>
```
ir nepareizā vietā, kas noved pie tā, ka pēc testa beigām nevar nospiest navigācijas linkus. Šim divam būtu jābūt starp "navbar-menu" un "saturs" diviem, pašlaik tas ir iekšā "saturs" divā. Tas gan arī neatrisināja šo problēmu, bt vajadzētu salabot :)

**Comment by in24** [comment]
Laikam strādā

**Comment by GundegaDekena** [comment]
Salabots ar #39
